### ISSUE TITLE
Servo Alignment / 12=00? / Wiring

### ISSUE THREAD

**Issue by BzowK** [3KUdelta/ESP32_ServoClock_MST#2]
Good Day, Again - 

I've got two issues I've spent time trying to resolve without luck - hoping you can help...

**Servo Alignment**
So I finally got everything put together  and seemingly the sketch working, but when I powered it up, most of the segments (which I fortunately hadn't screwed in yet) went flying as it rotated them all over the place.  I added serial prints into part of the sketch so I could see which numbers it was trying to display, reattached the segments, then reset; but many went flying again :(  Not sure what the opening sequence is, but how do you suggest I proceed?

**12 Hour Clock**
I live in the US and (if I did it correctly) the serial prints are showing "00:45" for "12:45."  When not in a "12" hour, it outputs correctly.  Is there an easy code change to adjust this?  Note: The only changes I made to the time in the sketch were to define "TZ" as "6" and "UTC_OFFSET - TZ" to subtract 6 hours from the TZ as I'm Central time (US).  Here's my current sketch minus SSID/Password...
[ServoClockGen.ino.txt](https://github.com/3KUdelta/ESP32_ServoClock_MST/files/5030179/ServoClockGen.ino.txt)

**Wiring**
When initially hooking everything up, I couldn't get it to work at all.  I eventually found this post that the SCL & SDA wires should be hooked up in reverse to what your diagram showed.  Once I swapped them, it started to (theoretically) work.  I made a new Fritzing image which I pasted below as an example of what worked for me. 

Any suggestions would be appreciated - Thanks!

**UPDATE**
I think I got the first one set where I can get the segments close to correct.  Not sure in sketch how to fine tune each, though.

**Comment by 3KUdelta** [comment]
Hi
I hope I can help you with your questions:
Servo Alignment, please use this part of the code:
`const int servofinetune [4] [7] = {      // pulse to add to servopulse for fine tunning of each individual servo
  { -25, 0, 0, 10, -30, 0, -20},
  {0, -20, 0, -10, -55, -5, 30},
  {0, -20, -15, 0, 0, 0, 0},
  {20, 20, -10, 0, 10, -10, 10}
};`

Each group represents one digit with the corresponding 7 servos. E.g. {servo0, servo1, ... }. The initial sequence puts all servos to ON. Then unplug the power. Observe the state of the servos and put a correction factor for each servo. For my build I had to correct the first servo -25. It was overshooting. You need to try this out a several times.

Time Zone and 12 hour display:
Unfortunately for you,  the code was built for European usage and automatic calculation of DST for Europe. The settings for your time zone in general are fine. The DST is an extra calculation. Therefore your changes need to consider exchanging the rules for the daylight saving time for your region. This code at the end needs to be adjusted to your rules:
` boolean summertime_EU(int year, byte month, byte day, byte hour, byte tzHours)
// European Daylight Savings Time calculation by "jurs" for German Arduino Forum
// input parameters: "normal time" for year, month, day, hour and tzHours (0=UTC, 1=MEZ)
// return value: returns true during Daylight Saving Time, false otherwise
{
  if (month < 3 || month > 10) return false; // no changes in Jan, Feb, Nov, Dec
  if (month > 3 && month < 10) return true;  // changes in Apr, May, Jun, Jul, Aug, Sep
  if (month == 3 && (hour + 24 * day) >= (1 + tzHours + 24 * (31 - (5 * year / 4 + 4) % 7)) || month == 10 && (hour + 24 * day) < (1 + tzHours + 24 * (31 - (5 * year / 4 + 1) % 7)))
    return true;
  else
    return false;
} // end of summertime_EU()`

If you want to change the 24 hour display to 12 hour you need to deduct 12 hours if time larger than 11. 
This should work at the end of the function void get_NTP_time(): 
If (hour(now()) >=12) adjustTime(-43200); // 43200 seconds = 12 hours

The wiring should be as indicated in the text. The picture might be misleading. 
    PIN Connections on ESP32
    21 -- SLA
    22 -- SLC
     0 -- OA

Hope this helps.

**Comment by BzowK** [comment]
Really appreciate your reply.  Just updated sketch and going to work on it this weekend.  Closing out this issue - hoping it doesn't jinx me :)  

Thanks
